name: Check Version

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if new version 
        run: |
          EXTERN_LATEST=$(curl --header "X-GitHub-Api-Version:2022-11-28"  https://api.github.com/repos/playwright-community/playwright-go/releases | jq '.[1].tag_name')
          LOCAL_LATEST=$(curl --header "X-GitHub-Api-Version:2022-11-28"  https://api.github.com/repos/manfromth3m0oN/playwright-go/releases | jq '.[1].tag_name')
          LATEST=$(echo "$EXTERN_LATEST\n$LOCAL_LATEST" | sort -V | tail -n 1)
          sed -r 's/playwright@(v[0-9]+.[0-9]+.[0-9])/playwright@'$LATEST'/g' Dockerfile 
